from .document_manager import DocumentManager
from .text_editor import TextEditor
from .suggestions_panel import SuggestionsPanel
from .settings_panel import SettingsPanel
from .popup_windows.prompt_customization_popup import PromptCustomizationPopup